"""Add fuel type/quantity/amount to MouvementCarburant

Revision ID: 02db2d0d966f
Revises: ed969fa87800
Create Date: 2026-09-11 11:12:40.134634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02db2d0d966f'
down_revision = 'ed969fa87800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mouvements_carburant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_gaz', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('quantite_litres', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mouvements_carburant', schema=None) as batch_op:
        batch_op.drop_column('montant')
        batch_op.drop_column('quantite_litres')
        batch_op.drop_column('type_gaz')

    # ### end Alembic commands ###
