"""Add fuel ticket tracking (Carburant)

Revision ID: 03b233492cde
Revises: b711fa67fa05
Create Date: 2026-09-09 07:39:57.700984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b233492cde'
down_revision = 'b711fa67fa05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_carburant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seuil_alerte', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demandes_carburant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_demande', sa.DateTime(), nullable=True),
    sa.Column('demande_par_id', sa.Integer(), nullable=False),
    sa.Column('stock_au_moment', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('traite_le', sa.DateTime(), nullable=True),
    sa.Column('traite_par_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['demande_par_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['traite_par_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouvements_carburant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type_mouvement', sa.String(length=15), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('beneficiaire', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('enregistre_par_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enregistre_par_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mouvements_carburant')
    op.drop_table('demandes_carburant')
    op.drop_table('config_carburant')
    # ### end Alembic commands ###
