"""add beneficiaire to depenses

Revision ID: 083feb31f2f8
Revises: 40332b875f61
Create Date: 2026-08-20 11:05:54.718833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083feb31f2f8'
down_revision = '40332b875f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beneficiaire', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depenses', schema=None) as batch_op:
        batch_op.drop_column('beneficiaire')

    # ### end Alembic commands ###
