"""Add device replacement requests (demandes_appareil)

Revision ID: 129784f438fa
Revises: 826a2fce8211
Create Date: 2026-08-20 05:14:13.483558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129784f438fa'
down_revision = '826a2fce8211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demandes_appareil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appareil_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('date_demande', sa.DateTime(), nullable=True),
    sa.Column('date_traitement', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appareil_id'], ['appareils.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demandes_appareil')
    # ### end Alembic commands ###
