"""Add payslip breakdown fields

Revision ID: 2571f6d5026d
Revises: dda845838527
Create Date: 2026-08-19 14:21:56.336451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2571f6d5026d'
down_revision = 'dda845838527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_bulletin', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('salaire_base', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('primes', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('primes_detail', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('retenues', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('retenues_detail', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('jours_travailles', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('jours_absence', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['numero_bulletin'])

    # Backfill existing rows: montant was previously the base salary with no primes/retenues.
    op.execute("UPDATE salaires SET salaire_base = montant")
    op.execute("UPDATE salaires SET numero_bulletin = 'BUL-' || annee || lpad(mois::text, 2, '0') || '-' || lpad(id::text, 4, '0')")

    with op.batch_alter_table('salaires', schema=None) as batch_op:
        batch_op.alter_column('salaire_base', server_default=None)
        batch_op.alter_column('primes', server_default=None)
        batch_op.alter_column('retenues', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaires', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('note')
        batch_op.drop_column('jours_absence')
        batch_op.drop_column('jours_travailles')
        batch_op.drop_column('retenues_detail')
        batch_op.drop_column('retenues')
        batch_op.drop_column('primes_detail')
        batch_op.drop_column('primes')
        batch_op.drop_column('salaire_base')
        batch_op.drop_column('numero_bulletin')

    # ### end Alembic commands ###
