"""remove fournisseur link from depenses

Revision ID: 40332b875f61
Revises: 89fe21ffb6a0
Create Date: 2026-08-20 10:59:35.651390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40332b875f61'
down_revision = '89fe21ffb6a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depenses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('depenses_fournisseur_id_fkey'), type_='foreignkey')
        batch_op.drop_column('fournisseur_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fournisseur_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('depenses_fournisseur_id_fkey'), 'fournisseurs', ['fournisseur_id'], ['id'])

    # ### end Alembic commands ###
