"""Add monthly consommables tracking

Revision ID: 46d97c52c99b
Revises: d068416221b0
Create Date: 2026-08-20 07:04:44.674527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d97c52c99b'
down_revision = 'd068416221b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consommables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('suivi_consommables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consommable_id', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paye', sa.Boolean(), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['consommable_id'], ['consommables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consommable_id', 'mois', 'annee', name='uq_suivi_consommable_mois_annee')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suivi_consommables')
    op.drop_table('consommables')
    # ### end Alembic commands ###
