"""add contact and identity fields to users

Revision ID: 5f5594113846
Revises: e6b134912b20
Create Date: 2026-08-25 14:42:36.366528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5594113846'
down_revision = 'e6b134912b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telephone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('adresse', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('date_naissance', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('sexe', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('numero_piece_identite', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('numero_piece_identite')
        batch_op.drop_column('sexe')
        batch_op.drop_column('date_naissance')
        batch_op.drop_column('adresse')
        batch_op.drop_column('telephone')

    # ### end Alembic commands ###
