"""add demandes_absence table

Revision ID: 60100c125d39
Revises: 5f5594113846
Create Date: 2026-08-25 15:08:11.703557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60100c125d39'
down_revision = '5f5594113846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demandes_absence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('motif', sa.String(length=20), nullable=False),
    sa.Column('precision', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('commentaire_admin', sa.Text(), nullable=True),
    sa.Column('traite_le', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demandes_absence')
    # ### end Alembic commands ###
