"""Add employee login/logout history

Revision ID: 6cc0252badc5
Revises: 4a3e2fb9b5c0
Create Date: 2026-08-19 16:10:52.884926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc0252badc5'
down_revision = '4a3e2fb9b5c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connexions_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('type_evenement', sa.String(length=10), nullable=False),
    sa.Column('date_heure', sa.DateTime(), nullable=False),
    sa.Column('adresse_ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connexions_log')
    # ### end Alembic commands ###
