"""add validation lock to depenses

Revision ID: 787acb08e4cb
Revises: e5ad7aa96659
Create Date: 2026-08-20 12:42:00.679514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787acb08e4cb'
down_revision = 'e5ad7aa96659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valide', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('valide_le', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depenses', schema=None) as batch_op:
        batch_op.drop_column('valide_le')
        batch_op.drop_column('valide')

    # ### end Alembic commands ###
