"""add validation lock to transactions bancaires

Revision ID: 7bd9d80e0212
Revises: 4d8edaf27b0f
Create Date: 2026-08-20 19:40:04.159927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bd9d80e0212'
down_revision = '4d8edaf27b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions_bancaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valide', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('valide_le', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions_bancaires', schema=None) as batch_op:
        batch_op.drop_column('valide_le')
        batch_op.drop_column('valide')

    # ### end Alembic commands ###
