"""Add company devices (appareils) tracking

Revision ID: 826a2fce8211
Revises: 6cc0252badc5
Create Date: 2026-08-20 04:59:37.641429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826a2fce8211'
down_revision = '6cc0252badc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appareils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_appareil', sa.String(length=50), nullable=False),
    sa.Column('marque', sa.String(length=100), nullable=True),
    sa.Column('modele', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('employe_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('date_attribution', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('remplace_par_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.ForeignKeyConstraint(['remplace_par_id'], ['appareils.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appareils')
    # ### end Alembic commands ###
