"""add sortie window to horaire_programme and sessions_presence

Revision ID: 89fe21ffb6a0
Revises: 94e353685943
Create Date: 2026-08-20 10:34:47.496615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89fe21ffb6a0'
down_revision = '94e353685943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horaire_programme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heure_debut_sortie', sa.Time(), nullable=False, server_default='17:00:00'))
        batch_op.add_column(sa.Column('heure_fin_sortie', sa.Time(), nullable=False, server_default='17:30:00'))
        batch_op.drop_column('heure_sortie_prevue')

    with op.batch_alter_table('horaire_programme', schema=None) as batch_op:
        batch_op.alter_column('heure_debut_sortie', server_default=None)
        batch_op.alter_column('heure_fin_sortie', server_default=None)

    with op.batch_alter_table('sessions_presence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heure_debut_sortie', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('heure_fin_sortie', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions_presence', schema=None) as batch_op:
        batch_op.drop_column('heure_fin_sortie')
        batch_op.drop_column('heure_debut_sortie')

    with op.batch_alter_table('horaire_programme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heure_sortie_prevue', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.drop_column('heure_fin_sortie')
        batch_op.drop_column('heure_debut_sortie')

    # ### end Alembic commands ###
