"""add bank payment link to depenses

Revision ID: 8b6a797185a0
Revises: fa7b392f3eab
Create Date: 2026-08-20 18:20:55.015113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6a797185a0'
down_revision = 'fa7b392f3eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode_paiement', sa.String(length=20), nullable=False, server_default='cash'))
        batch_op.add_column(sa.Column('libelle_bancaire', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reference_paiement', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('transaction_bancaire_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'transactions_bancaires', ['transaction_bancaire_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('depenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('transaction_bancaire_id')
        batch_op.drop_column('reference_paiement')
        batch_op.drop_column('libelle_bancaire')
        batch_op.drop_column('mode_paiement')

    # ### end Alembic commands ###
