"""add evenements_agenda table

Revision ID: 8d35f0cced21
Revises: 60100c125d39
Create Date: 2026-09-02 13:42:20.416047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d35f0cced21'
down_revision = '60100c125d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evenements_agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=True),
    sa.Column('heure_fin', sa.Time(), nullable=True),
    sa.Column('lieu', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cree_par_id', sa.Integer(), nullable=False),
    sa.Column('vu_par_admin', sa.Boolean(), nullable=False),
    sa.Column('annule', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evenements_agenda')
    # ### end Alembic commands ###
