"""Add plan_comptable table

Revision ID: 949b67e8c8a4
Revises: 9794a6649dc0
Create Date: 2026-09-03 11:36:07.806882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949b67e8c8a4'
down_revision = '9794a6649dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_comptable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_comptable')
    # ### end Alembic commands ###
