"""add horaire_programme config table

Revision ID: 94e353685943
Revises: e3e674b052fa
Create Date: 2026-08-20 10:22:23.997408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e353685943'
down_revision = 'e3e674b052fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horaire_programme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heure_debut_entree', sa.Time(), nullable=False),
    sa.Column('heure_fin_entree', sa.Time(), nullable=False),
    sa.Column('heure_sortie_prevue', sa.Time(), nullable=True),
    sa.Column('jours_actifs', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horaire_programme')
    # ### end Alembic commands ###
