"""add clients_commercial table

Revision ID: 9794a6649dc0
Revises: a1ce346e40db
Create Date: 2026-09-02 15:13:27.090533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9794a6649dc0'
down_revision = 'a1ce346e40db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients_commercial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_contact', sa.Date(), nullable=False),
    sa.Column('nom_client', sa.String(length=150), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('type_client', sa.String(length=20), nullable=False),
    sa.Column('type_client_precision', sa.String(length=150), nullable=True),
    sa.Column('budget', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('villa_interessee', sa.String(length=150), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('prochaine_relance', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cree_par_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cree_par_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients_commercial')
    # ### end Alembic commands ###
