"""add factures_fournisseur table

Revision ID: 9d4499cb6e40
Revises: e80ec37ecab2
Create Date: 2026-08-20 11:28:14.975287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4499cb6e40'
down_revision = 'e80ec37ecab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factures_fournisseur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fournisseur_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('date_facture', sa.Date(), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=True),
    sa.Column('montant_brut', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factures_fournisseur')
    # ### end Alembic commands ###
