"""add type_evenement to evenements_agenda

Revision ID: a1ce346e40db
Revises: 8d35f0cced21
Create Date: 2026-09-02 13:56:43.818929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ce346e40db'
down_revision = '8d35f0cced21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evenements_agenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_evenement', sa.String(length=20), nullable=False, server_default='reunion'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evenements_agenda', schema=None) as batch_op:
        batch_op.drop_column('type_evenement')

    # ### end Alembic commands ###
