"""Add Salaire.depense_id link

Revision ID: b711fa67fa05
Revises: 949b67e8c8a4
Create Date: 2026-09-03 13:04:25.084408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b711fa67fa05'
down_revision = '949b67e8c8a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depense_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'depenses', ['depense_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaires', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('depense_id')

    # ### end Alembic commands ###
