"""Add structured device history log

Revision ID: d068416221b0
Revises: 129784f438fa
Create Date: 2026-08-20 06:28:40.906089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd068416221b0'
down_revision = '129784f438fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historique_appareil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appareil_id', sa.Integer(), nullable=False),
    sa.Column('type_evenement', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_evenement', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appareil_id'], ['appareils.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historique_appareil')
    # ### end Alembic commands ###
