"""Add detailed employee fields

Revision ID: dda845838527
Revises: 42d9c7a97e13
Create Date: 2026-08-19 14:15:14.137728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda845838527'
down_revision = '42d9c7a97e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matricule', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('departement', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telephone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('adresse', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('date_naissance', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('sexe', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('numero_piece_identite', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('date_embauche', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('type_contrat', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('mode_paiement', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('numero_compte', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['matricule'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('numero_compte')
        batch_op.drop_column('mode_paiement')
        batch_op.drop_column('type_contrat')
        batch_op.drop_column('date_embauche')
        batch_op.drop_column('numero_piece_identite')
        batch_op.drop_column('sexe')
        batch_op.drop_column('date_naissance')
        batch_op.drop_column('adresse')
        batch_op.drop_column('email')
        batch_op.drop_column('telephone')
        batch_op.drop_column('departement')
        batch_op.drop_column('matricule')

    # ### end Alembic commands ###
