"""add heure_sortie to presences

Revision ID: e3e674b052fa
Revises: 46d97c52c99b
Create Date: 2026-08-20 10:09:06.381308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e674b052fa'
down_revision = '46d97c52c99b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heure_sortie', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presences', schema=None) as batch_op:
        batch_op.drop_column('heure_sortie')

    # ### end Alembic commands ###
