"""add validation lock to factures fournisseur

Revision ID: e5ad7aa96659
Revises: 35ea4e48ea93
Create Date: 2026-08-20 12:33:56.464436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ad7aa96659'
down_revision = '35ea4e48ea93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factures_fournisseur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valide', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('valide_le', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factures_fournisseur', schema=None) as batch_op:
        batch_op.drop_column('valide_le')
        batch_op.drop_column('valide')

    # ### end Alembic commands ###
