"""Add Fournisseur.date_facture_initiale

Revision ID: ed969fa87800
Revises: 03b233492cde
Create Date: 2026-09-11 11:06:50.384984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed969fa87800'
down_revision = '03b233492cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fournisseurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_facture_initiale', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fournisseurs', schema=None) as batch_op:
        batch_op.drop_column('date_facture_initiale')

    # ### end Alembic commands ###
