"""add validation lock to suivi_consommables

Revision ID: f06a14caf255
Revises: 787acb08e4cb
Create Date: 2026-08-20 12:49:22.800214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06a14caf255'
down_revision = '787acb08e4cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suivi_consommables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valide', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('valide_le', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suivi_consommables', schema=None) as batch_op:
        batch_op.drop_column('valide_le')
        batch_op.drop_column('valide')

    # ### end Alembic commands ###
