"""replace recettes with compte bancaire ledger

Revision ID: fa7b392f3eab
Revises: f06a14caf255
Create Date: 2026-08-20 17:50:28.345109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa7b392f3eab'
down_revision = 'f06a14caf255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compte_bancaire_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solde_initial', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions_bancaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('beneficiaire', sa.String(length=150), nullable=True),
    sa.Column('libelle', sa.String(length=255), nullable=True),
    sa.Column('reference_paiement', sa.String(length=100), nullable=True),
    sa.Column('montant', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sens', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # Préserve l'historique des recettes existantes en les reprenant comme transactions
    # bancaires "débit" (entrée d'argent), avant de supprimer l'ancienne table.
    op.execute(
        "INSERT INTO transactions_bancaires (date, beneficiaire, libelle, montant, sens, created_at) "
        "SELECT date, source, description, montant, 'debit', created_at FROM recettes"
    )

    op.drop_table('recettes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recettes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('montant', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('recettes_pkey'))
    )
    op.drop_table('transactions_bancaires')
    op.drop_table('compte_bancaire_config')
    # ### end Alembic commands ###
